spring.application.name=api
# Puerto donde correrá nuestra API
server.port=8080

# Configuración de conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/techstore_db
spring.datasource.username=postgres
spring.datasource.password=admin

# Magia de Hibernate: Crea o actualiza las tablas automáticamente basándose en tus clases @Entity
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Para ver las consultas SQL en la consola (útil para el video)
spring.jpa.show-sql=true